name: Daily Deploy to Azure Static Web App

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 06:00 UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Dist Folder to Azure

    steps:
      - uses: actions/checkout@v3
        with:
          ref: report-output      # <-- checkout report-output branch
          submodules: true
          lfs: false

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_BUSH_02F213403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Auto-provided by GitHub Actions
          action: "upload"
          app_location: "./dist"
          api_location: ""
          output_location: ""
