name: Daily Deploy to Azure Static Web App

on:
  workflow_run:
    workflows: ["Generate Daily Currency Report"]
    types:
      - completed
  workflow_dispatch:  # Optional: still allow manual trigger

jobs:
  deploy_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy Dist Folder to Azure
    environment: production  # Deploy to production environment

    steps:
      - uses: actions/checkout@v3
        with:
          ref: report-output      # <-- checkout report-output branch
          submodules: true
          lfs: false

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_BUSH_02F213403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./dist"
          api_location: ""
          output_location: ""
