name: Daily Deploy to Azure Static Web App

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 06:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Dist Folder to Azure
    permissions:
      id-token: write       # Required for OIDC-based auth
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const core = require('@actions/core');
            return await core.getIDToken();
          result-encoding: string

      - name: Deploy to Azure Static Web App
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_BUSH_0D0694203 }}
          github_id_token: ${{ steps.idtoken.outputs.result }}
          action: "upload"
          app_location: "/dist"
