name: Generate Daily Currency Report

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 05:00 UTC (1h before deploy)
  workflow_dispatch:

jobs:
  generate_report:
    runs-on: ubuntu-latest
    name: Generate HTML report into /dist
    environment: production  # Deploy to production environment

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate_report.py
        run: python scripts/generate_report.py
        env:
          METAL_API_KEY: ${{ secrets.METAL_API_KEY }}
          TEST_MODE: "false" # Set to "true" to skip metal API in test mode

      - name: Commit and push /dist folder to report-output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Backup dist folder safely
          mv dist .dist-temp

          # Fetch the remote branch
          git fetch origin

          if git ls-remote --exit-code --heads origin report-output; then
            # Remote branch exists — check if we have a local version
            if git show-ref --verify --quiet refs/heads/report-output; then
              # Local branch exists, switch and reset to remote
              git switch report-output
              git reset --hard origin/report-output
            else
              # Local branch doesn't exist, create it tracking remote
              git switch -c report-output origin/report-output
            fi
          else
            # Remote branch does not exist, create a fresh orphan branch
            git switch --orphan report-output
            git rm -rf . --ignore-unmatch # Clean working directory completely
          fi

          # ✅ Confirm the current branch (for debugging/logging)
          git branch --show-current

          # Clean all except .git and dist backup
          find . -mindepth 1 -maxdepth 1 ! -name .git ! -name .dist-temp -exec rm -rf {} +

          # Restore new dist folder
          mv .dist-temp dist

          # Commit if changes exist
          git add dist/

          # Stage deletions and modifications everywhere else
          git add -u

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "🤖 Update daily currency report"
            git push origin report-output
          fi
