name: Generate Daily Currency Report - Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  generate_report:
    runs-on: ubuntu-latest
    name: Generate HTML report into /dist
    environment: staging

    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate_report.py
        run: python scripts/generate_report.py
        env:
          METAL_API_KEY: ${{ secrets.METAL_API_KEY }}
          TEST_MODE: "true"

      - name: Commit and push /dist folder to report-output-staging branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          mv dist .dist-temp

          git fetch origin report-output-staging

          if git show-ref --verify --quiet refs/heads/report-output-staging; then
            git switch report-output-staging
            git reset --hard origin/report-output-staging
          else
            git switch -c report-output-staging origin/report-output-staging
          fi

          git branch --show-current

          find . -mindepth 1 -maxdepth 1 ! -name .git ! -name .dist-temp -exec rm -rf {} +

          mv .dist-temp dist

          git add dist/
          git add -u

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "🧪 Update staging currency report"
            git push origin report-output-staging
          fi
