name: Generate Daily Currency Report

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 05:00 UTC (1h before deploy)
  workflow_dispatch:

jobs:
  generate_report:
    runs-on: ubuntu-latest
    name: Generate HTML report into /dist

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate_report.py
        run: python scripts/generate_report.py
        env:
          METAL_API_KEY: ${{ secrets.METAL_API_KEY }}

      - name: Commit and push /dist folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/index.html dist/Logo_jfn_github.png
          git commit -m "🤖 Update daily currency report"
          git push
